CREATE TABLE IF NOT EXISTS gauge_metrics (
		id      VARCHAR (255) PRIMARY KEY,
		value   DOUBLE PRECISION NOT NULL
	);
	CREATE TABLE IF NOT EXISTS counter_metrics (
		id      VARCHAR (255) PRIMARY KEY,
		value   BIGSERIAL NOT NULL
	);